# Generated by Django 3.1.1 on 2020-09-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Admin_profile',
            field=models.ImageField(default=1, upload_to='images/Admin_profile/'),
        ),
    ]
