# Generated by Django 3.1.1 on 2020-09-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminManagement', '0002_admin_admin_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='Admin_contact',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
