# Generated by Django 3.1.1 on 2020-09-21 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
        ('PostManagement', '0001_initial'),
        ('CommentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='PostManagement.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.user'),
        ),
    ]
