# Generated by Django 3.1.1 on 2020-09-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentManagement', '0002_auto_20200921_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_description',
            field=models.TextField(max_length=5000),
        ),
    ]
