# Generated by Django 3.1.1 on 2020-09-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_auto_20200930_2214'),
        ('CommentManagement', '0004_auto_20200930_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='User',
        ),
        migrations.AddField(
            model_name='comment',
            name='Profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.profile'),
        ),
    ]
