# Generated by Django 3.1.1 on 2020-09-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommentManagement', '0005_auto_20201001_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Profile',
        ),
    ]
