# Generated by Django 3.1.1 on 2020-09-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_auto_20201001_0128'),
        ('CommentManagement', '0006_remove_comment_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.user'),
        ),
    ]
