# Generated by Django 2.2 on 2020-09-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostManagement', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Post_description2',
            field=models.TextField(max_length=100000, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='post',
            name='Post_description3',
            field=models.TextField(max_length=100000, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='post',
            name='Post_image',
            field=models.ImageField(null='true', upload_to=''),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='post',
            name='Post_image2',
            field=models.ImageField(null='true', upload_to=''),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='post',
            name='Post_image3',
            field=models.ImageField(null='true', upload_to=''),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='post',
            name='Post_catagory',
            field=models.CharField(choices=[('Regions', 'Regions'), ('Popular Places', 'Popular Places'), ('Blog', 'Blog')], default='Blog', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='User',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User'),
        ),
    ]
