# Generated by Django 2.2 on 2020-09-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostManagement', '0003_auto_20200928_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_description2',
            field=models.TextField(blank='true', max_length=100000, null='true'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Post_description3',
            field=models.TextField(blank='true', max_length=100000, null='true'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Post_image2',
            field=models.ImageField(blank='true', null='true', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='Post_image3',
            field=models.ImageField(blank='true', null='true', upload_to=''),
        ),
    ]
