# Generated by Django 2.2 on 2020-09-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostManagement', '0004_auto_20200928_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_image2',
            field=models.ImageField(blank='true', default=1, null='true', upload_to=''),
        ),
    ]
