# Generated by Django 2.2 on 2020-09-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostManagement', '0005_auto_20200928_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Post_description2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Post_description3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Post_image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Post_image3',
        ),
    ]
