# Generated by Django 3.1.1 on 2020-09-30 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PostManagement', '0006_auto_20200928_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='User',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
