# Generated by Django 3.1.1 on 2020-09-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_auto_20200930_2214'),
        ('PostManagement', '0007_auto_20200930_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='User',
        ),
        migrations.AddField(
            model_name='post',
            name='Profile',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.profile'),
            preserve_default='true',
        ),
    ]
