# Generated by Django 3.1.1 on 2020-09-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_auto_20200930_2214'),
        ('PostManagement', '0008_auto_20201001_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.profile'),
        ),
    ]
