# Generated by Django 3.1.1 on 2020-09-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostManagement', '0012_auto_20201001_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Profile',
        ),
    ]
