# Generated by Django 3.1.1 on 2020-09-30 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostManagement', '0013_remove_post_profile'),
        ('UserManagement', '0006_auto_20201001_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='UserManagement.user'),
            preserve_default='true',
        ),
    ]
