# Generated by Django 3.1.1 on 2020-09-30 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostManagement', '0014_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='User',
        ),
    ]
