# Generated by Django 2.2 on 2020-10-01 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileManagement', '0001_initial'),
        ('PostManagement', '0015_remove_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProfileManagement.Profile'),
        ),
    ]
