# Generated by Django 2.2 on 2020-09-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_profile',
            field=models.ImageField(default=1, upload_to='images/userprofile/'),
        ),
        migrations.AddField(
            model_name='user',
            name='constitution',
            field=models.FileField(default=1, upload_to='files/constitution/'),
        ),
    ]
