# Generated by Django 2.2 on 2020-09-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20200928_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_profile',
            field=models.ImageField(default=1, upload_to='images/User_profile/'),
        ),
    ]
