# Generated by Django 3.1.1 on 2020-09-30 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommentManagement', '0004_auto_20200930_2214'),
        ('PostManagement', '0007_auto_20200930_2214'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManagement', '0004_auto_20200930_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Full_name', models.CharField(max_length=100)),
                ('User_email', models.EmailField(max_length=100, unique=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('User_profile_picture', models.ImageField(default=1, upload_to='images/User_profile_picture/')),
                ('constitution', models.FileField(default=1, upload_to='files/constitution/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
