# Generated by Django 3.1.1 on 2020-09-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostManagement', '0013_remove_post_profile'),
        ('CommentManagement', '0006_remove_comment_profile'),
        ('UserManagement', '0005_auto_20200930_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=100)),
                ('User_email', models.EmailField(max_length=100, unique=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('User_profile', models.ImageField(default=1, upload_to='images/User_profile/')),
                ('constitution', models.FileField(default=1, upload_to='files/constitution/')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
